version: 1.0.0
services: 
  app:
    build: . 
    ports:
      - "8000:8000"
    links:
      - dynamodb
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}