version: 1.0.0
services: 
  app:
    build: . 
    ports:
      - "8000:8000"
    links:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SECRET_JWT=${SECRET_JWT}